name: roll_dice
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/dice-six-faces-one.png
    - assets/images/dice-six-faces-two.png
    - assets/images/dice-six-faces-three.png
    - assets/images/dice-six-faces-four.png
    - assets/images/dice-six-faces-five.png
    - assets/images/dice-six-faces-six.png
